#!/bin/bash

rm -Rf test_struct
randfolder=$((RANDOM%6+1))
randfile=$((RANDOM%3+1))
mkdir -p test_struct/folder{1,2,3,4,5,6}
touch test_struct/folder{1,2,3,4,5,6}/file{1,2,3}
cp specimen test_struct/folder${randfolder}/file${randfile}
